// <auto-generated />
using System;
using Clean.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clean.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240217225814_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clean.Core.Entities.clients", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"), 1L, 1);

                    b.Property<string>("AdressClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeClient")
                        .HasColumnType("int");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Clean.Core.Entities.doctors", b =>
                {
                    b.Property<int>("IdDoctors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoctors"), 1L, 1);

                    b.Property<int>("HoursDoctors")
                        .HasColumnType("int");

                    b.Property<string>("NameDoctors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SalaryDoctors")
                        .HasColumnType("int");

                    b.HasKey("IdDoctors");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Clean.Core.Entities.turns", b =>
                {
                    b.Property<string>("NumTurn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTimeTurn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailableTurn")
                        .HasColumnType("bit");

                    b.Property<int>("NumRoom")
                        .HasColumnType("int");

                    b.HasKey("NumTurn");

                    b.ToTable("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
